[package]
name = "rust-xp-aya-ebpf-common"
version = "0.1.0"
edition = "2021"

license.workspace = true

[features]
default = []
user = ["aya"]

[dependencies]
aya = { workspace = true, optional = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }

[lib]
path = "src/lib.rs"
