group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true
unstable_features = true
hard_tabs = true                   # no comment
edition = "2021"
max_width = 120
chain_width = 80
array_width = 80
