[rule]
id = "credential-access-tools"
description = "Execution of a binary commonly used to harvest credentials from memory or disk"
severity = "critical"

[[rule.conditions]]
field = "process.filepath"
op = "regex"
value = "/(mimipenguin|lazagne|gosecretsdump|swap_digger|3snake)$"
